version: "3.9"

volumes:
  pg-data:
  redis-data:

services:
  postgres:
    build:
      context: .
      dockerfile: ./postgres.Dockerfile
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=1234
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
