volumes:
  pg-data:
  redis-data:

services:
  postgres:
    build:
      context: .
      dockerfile: ./postgres.Dockerfile
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
