log_level = "debug"
debug = false

[server]
url = "http://localhost:8080"
client_timeout = "1s"

[redis]
addr = ":6379"
write_timeout = "1s"
read_timeout = "1s"
pool_size = 1

[cache]
state_ttl = "30m"
identity_ttl = "24h"
